inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

# Set a slightly bigger default, and ignore ABC failures in the tests.
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'test/**/*.rb'

# Ignore block length failures in the tests.
Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

# Ignore class length failures in the tests.
Metrics/ClassLength:
  Exclude:
    - 'test/**/*.rb'

# Ignore method length failures in the tests.
Metrics/MethodLength:
  Exclude:
    - 'test/**/*.rb'

# Ignore module length failures in the tests.
Metrics/ModuleLength:
  Exclude:
    - 'test/**/*.rb'

# Allow compact child definitions in the tests for brevity.
Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb
