require: rubocop-performance
inherit_from: .rubocop_todo.yml

AllCops:
  TargetRubyVersion: 2.4
  NewCops: enable

# Set a slightly bigger default, and ignore ABC failures in the tests.
# Also ignore in the CPU instructions files, which are unavoidably big.
Metrics/AbcSize:
  Max: 25
  Exclude:
    - 'lib/mos6502/cpu_instructions.rb'
    - 'lib/mos6502/cpu_illegal_instructions.rb'
    - 'lib/mos6502/cpu_ops.rb'
    - 'test/**/*.rb'

# Ignore block length failures in the tests.
Metrics/BlockLength:
  Exclude:
    - 'test/**/*.rb'

# Ignore class length failures in the tests.
# Also ignore in the CPU instructions files, which are unavoidably big.
Metrics/ClassLength:
  Exclude:
    - 'lib/mos6502/cpu_instructions.rb'
    - 'lib/mos6502/cpu_illegal_instructions.rb'
    - 'lib/mos6502/cpu_ops.rb'
    - 'test/**/*.rb'

# Set a slightly higher default for this.
# Also ignore the CPU instructions files, which look complex to this sort
# of tool, but aren't really.
Metrics/CyclomaticComplexity:
  Max: 10
  Exclude:
    - 'lib/mos6502/cpu_instructions.rb'
    - 'lib/mos6502/cpu_illegal_instructions.rb'

# Ignore method length failures in the tests.
# Also ignore in the CPU instructions files, which are unavoidably big.
Metrics/MethodLength:
  Exclude:
    - 'lib/mos6502/cpu_instructions.rb'
    - 'lib/mos6502/cpu_illegal_instructions.rb'
    - 'lib/mos6502/cpu_ops.rb'
    - 'test/**/*.rb'

# Ignore module length failures in the tests.
Metrics/ModuleLength:
  Exclude:
    - 'test/**/*.rb'

# Ignore parameter list lengths in the tests.
Metrics/ParameterLists:
  Exclude:
    - 'test/**/*.rb'

# Set a slightly higher default for this.
# Also ignore the CPU instructions files, which look complex to this sort
# of tool, but aren't really.
Metrics/PerceivedComplexity:
  Max: 10
  Exclude:
    - 'lib/mos6502/cpu_instructions.rb'
    - 'lib/mos6502/cpu_illegal_instructions.rb'

# Allow compact child definitions in the tests for brevity.
Style/ClassAndModuleChildren:
  Exclude:
    - test/**/*.rb

# Just allow simple formatting rules. We're not doing anything complex.
Style/FormatStringToken:
  EnforcedStyle: unannotated

# Symbol arrays should look obviously like symbol arrays.
Style/SymbolArray:
  EnforcedStyle: brackets
