---
dist: bionic
language: ruby

cache: bundler

before_install: gem install bundler -v 2.1.2

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

env:
  - MOS6502_KLAUS2M5=on

matrix:
  fast_finish: true
  include:
    - name: Rubocop
      rvm: 2.4
      script:
      - bundle info rubocop
      - bundle exec rubocop
  allow_failures:
    - rvm: ruby-head
