name: CI

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        ruby: [2.4, 2.5, 2.6, 2.7, head]
    env:
      MOS6502_KLAUS2M5: on
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
    - run: bundle install
    - run: bundle exec rake
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: false
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
        bundler-cache: true
    - run: bundle info rubocop
    - run: bundle exec rubocop
